### ISSUE TITLE
Column chart with multiple non-overlapping series

### ISSUE THREAD

**Issue by tpetricek** [TahaHachana/XPlot#14]
I was trying to create bar chart that would have different colors for different bars. 

I suspect the right way to do this in Google would be using the `{ role: 'style' }` thing in data table ([here is an example](https://developers.google.com/chart/interactive/docs/gallery/barchart)), but I guess this cannot be easily added to XPlot.

So I instead tried creating sequence of sequences with the differently coloured inputs. This behaves as expected when there are some overlaps, but it somehow "merges" the series when there are no overlaps:

    [ [1,1.0; 2,2.0]
      [2,1.0; 4,3.0] ]
    |> Chart.Column
    |> Chart.WithLabels ["First"; "Second"]
    |> Chart.WithLegend true

    [ [1,1.0; 2,2.0]
      [3,1.0; 4,3.0] ]
    |> Chart.Column
    |> Chart.WithLabels ["First"; "Second"]
    |> Chart.WithLegend true

![charts](https://cloud.githubusercontent.com/assets/485413/8015539/7a29c976-0ba7-11e5-8757-3e3b030ae745.png)

This might very well be some oddity in Google Charts that we cannot do anything with, but if we can solve this (or support `role: style`) that would be great.

**Comment by TahaHachana** [comment]
I opened a new issue for the roles support. For the second example, this is in fact the same problem as in #9 and it was supposed to be fixed in version 1.1.8. I think I solved the problem for good in 1.2.0.

**Comment by tpetricek** [comment]
Nice, thanks! I'll need to update the dependency in FsLab.
