### ISSUE TITLE
Missing POST parameters exception

### ISSUE THREAD

**Issue by tjaskula** [TahaHachana/XPlot#22]
Hello, I'm not able to create a single plot. Event if I take the one from the tutorial I end up with this exception in F# interactive :
```
System.Exception: Missing required POST parameters: platform un key origin args kwargs
   at XPlot.Plotly.Figure.Plot(String filename) in C:\Users\AHMED\Documents\GitHub\XPlot\src\XPlot.Plotly\Main.fs:line 560
   at <StartupCode$FSI_0003>.$FSI_0003.main@() in C:\Code\GitHub\BlogSupport\UnivarianteLinearReg\LinearRegressionXPlotPlotly.fsx:line 50
Stopped due to error
```

This may be linked to this http://community.plot.ly/t/electricimp-missing-required-post-parameters-platform-un-key-origin-args-kwargs/113

**Comment by TahaHachana** [comment]
Hello, I'm going to remove the need for calling the API which resolves this issue and allows faster plot generation.

**Comment by tjaskula** [comment]
Hi, another side question. I've pulled the code and cannot compile it. It seems that it lacks some of the modules like Figure,  Kwargs, etc. I've checked against Tomas Petricek repo where I found those parts. Could you point me to the right code base?

**Comment by TahaHachana** [comment]
The XPlot.Plotly project which is currently just a prototype for plotly.js support should build.

**Comment by dsyme** [comment]
I got this same error when I tried to use Plotly

**Comment by TahaHachana** [comment]
I published a [new version on NuGet](https://www.nuget.org/packages/XPlot.Plotly/) that solves this issue for good since there isn't an API round trip anymore. The documentation and the FsLab integration aren't up-to-date yet, it would be better if I test it a bit more.
```fsharp
let trace1 =
    Scatter(
        x = [1; 2; 3; 4],
        y = [10; 15; 13; 17],
        mode = "markers"
    )

let trace2 =
    Scatter(
        x = [2; 3; 4; 5],
        y = [16; 5; 11; 9],
        mode = "lines"
    )

let trace3 =
    Scatter(
        x = [1; 2; 3; 4],
        y = [12; 9; 15; 12],
        mode = "lines+markers"
    )

[trace1; trace2; trace3]
|> Plotly.Plot
|> Plotly.Show
```

**Comment by tjaskula** [comment]
Works like a charm for me. This is even more consistent approach with Google Charts. Much better. Thanks.
