### ISSUE TITLE
Plotly Offline Option

### ISSUE THREAD

**Issue by RussellPolitzky** [TahaHachana/XPlot#26]
Firstly, this is a suggestion, rather than an issue, as such.

Secondly, Plotly has recently released their offline API for R and Python and has open sourced the core JavaScript library.   This offline option is important for those working in the finance industry, since it removes security issues associated with sending data to a 3rd party for plotting.  I don't know what would be involved with regards modifying XPlot to offer a Plotly offline option, but I do think that it would solve the problem mentioned above and with that, potentially create a wider audience for XPlot and FsLab.

**Comment by TahaHachana** [comment]
The [latest version on NuGet](https://www.nuget.org/packages/XPlot.Plotly/) supports plotly.js and removes the API round trip. The FsLab integration isn't up do date yet, I'm [testing the new version](https://github.com/TahaHachana/XPlot/tree/master/src/XPlot.Plotly/Tests) and fixing the JSON schema mappings on the go.

**Comment by RussellPolitzky** [comment]
Hi there,

Thanks for this, that's good news.  Also, thank you for your work on this
part of the XPlot library as well as the others.

Regards,
Russell

On Sun, Jan 10, 2016 at 4:34 PM, Taha Hachana <notifications@github.com>
wrote:

> The latest version on NuGet <https://www.nuget.org/packages/XPlot.Plotly/>
> supports plotly.js and removes the API round trip. The FsLab integration
> isn't up do date yet, I'm testing the new version
> <https://github.com/TahaHachana/XPlot/tree/master/src/XPlot.Plotly/Tests>
> and fixing the JSON schema mappings on the go.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TahaHachana/XPlot/issues/26#issuecomment-170353563>.
>



-- 
Russell

**Comment by tpetricek** [comment]
I might have just updated the FsLab integration, though I have not done any proper testing!

**Comment by RussellPolitzky** [comment]
Hi All, 

 

Cool, thanks Tomas.  I have a small project in mind, which I’d like to try, hopefully in the next few months if time permits.  It essentially revolves around reporting and I’d like to pull a few things together with it, namely Fs Lab for the literate programming angle (ie. easy HTML rendering), the SQL Command type provider for painless SQL server access, a proprietary library for market data access and XPlot for charting.  The idea is to see if we can use this set of tools to develop high quality reports / analytics using a scripting paradigm.

 

At this point, I think we have all the required pieces in place to be able to do this in F#.

 

Russell

**Comment by RussellPolitzky** [comment]
Hi,

 

I’ve done a little testing.  Off line charts seem to be fine in FSI but weren’t working in the journal output.

I’ve added a few lines to the formatter to ensure that the plotly library is loaded once.

 

I’ve sent a pull request for the fix. 

 

Regards, 

Russell

**Comment by TahaHachana** [comment]
Thanks for the contribution
