### ISSUE TITLE
Plotly docs out of date?

### ISSUE THREAD

**Issue by tpetricek** [TahaHachana/XPlot#38]
I tried to randomly use on of the Plotly charts (http://tahahachana.github.io/XPlot/chart/plotly-heatmaps.html) and the docs seem to be out-of-date. Is that the case, or am I doing things wrong?

Also, if they are out of date, is there an issue tracking the progress on getting this fixed? Perhaps people can contribute?

**Comment by TahaHachana** [comment]
There is a working sample for each chart type now, I'll leave this issue open until all the old demos are online again.

**Comment by TahaHachana** [comment]
- [ ] Add all the Plotly demos back
