### ISSUE TITLE
Integrating XPlot with FsLab

### ISSUE THREAD

**Issue by tpetricek** [TahaHachana/XPlot#5]
Hello,
I spent a bit of time playing with XPlot recently and it looks great and very feature complete! 

I started [Foogle Charts](http://fsprojects.github.io/Foogle.Charts/) some time ago with the goal of wrapping some nice simple cross-platform visualization library (without too many external dependencies) to eventually replace [FSharp Charting](http://fslab.org/FSharp.Charting/) as the default visualization library for F# (FSharp Charting is still nice sometimes, but the fact that it is Windows only is becoming a big problem). Looking at XPlot, it looks like you did pretty much all the work already :-) so, I was thinking that we could abandon Foogle Charts and instead make XPlot the main library...

There are a couple of things that would be really nice to do in order to make integrating XPlot with FsLab and other data science projects easier - I'm happy to look into those and send PRs, but wanted to check with you first:

 1. **Adding a license** - I noticed the project does not have explicit license. Would you mind adding one? (I think Apache 2.0 would be perfect as most other F# projects use it, but anything compatible with it would probably work..)

 2. **Avoiding WPF dependency** - I tried using XPlot on Mac, but it didn't work well because of the WPF code that is used to show charts. In FsLab we just open a browser (which is poorer user experience, but it works everywhere). Could we extract the WPF code into a separate DLL, so that you get the XPlot behavior if you want, but FsLab can reference WPF-free "core" DLL?

 3. **Using ProjectScaffold** - All of the projects included in FsLab use Project Scaffold for building & documenting the code. Now, XPlot already has its own (and pretty nice) docs and releases, but I think it would still be valuable to use ProjectScaffold for this - mainly because following the same template makes it easy for others to contribute - they already know how things work (and I believe people also tend to trust OSS projects that use it).

I already did a little bit of work on (2) - see #6 - and I'm happy to create a prototype & PR for (3) so that we can discuss everything there (to make sure it would work for you).

**Comment by TahaHachana** [comment]
Hello Tomas, I added a license and merged #6. Regarding the migration to ProjectScaffold, it would be great if you guide me through the process. Meanwhile I'll finalize testing the plotly package and improving its API.

Feel free to indicate any other changes necessary to streamline the FsLab integration.

**Comment by tpetricek** [comment]
Thank you! 

I'll have a look at the ProjectScaffold PR and write a detailed comment when I send it (hopefully tomorrow, but might take a bit longer...).

**Comment by TahaHachana** [comment]
I published new packages so there is nothing standing in the integration's way. For now the old documentation is still online until the new one is ready.

**Comment by tpetricek** [comment]
Fantastic :-) both of the FsLab templates are now using this:

 - https://github.com/fslaborg/FsLab.Templates/commit/18abb622417407403a5d88efcc324081a43580a6
 - https://github.com/fslaborg/FsLab.Templates/commit/b2a2df630add8840dc82cfa288b1089dbbaf57c3

The second template actually looks *much nicer* with XPlot!

**Comment by tpetricek** [comment]
BTW @TahaHachana - If you are not a member yet, please consider joining the F# Data Science Google group: https://groups.google.com/group/fsharp-data-science. This is a place where a lot of the discussions about FsLab happen (and I'll send some announcement about XPlot there) & it's also a place where we can get more contributors for XPlot :-)

**Comment by TahaHachana** [comment]
I joined the group since it became public, thanks for the announcement email by the way. Issues #8, #9 and #10 have been fixed (even if #9 still concerns me).

**Comment by tpetricek** [comment]
Nice, thank you for all the help with this!
